### ISSUE TITLE
First Startup Issue / Airmon-ng Check Kill 

### ISSUE THREAD

**Issue by arianizadi** [esc0rtd3w/wifi-hacker#17]
Well i run the script, check the updates, apply, then wait 5 seconds for it to move on to main menu. But it gets stuck in a loop because it cant seem to kill the network manager. It is looping between Loading Menu.... and Network Manager is already running.

**Comment by esc0rtd3w** [comment]
thanks. i will look into it and maybe make a skip option in the meantime.

what distro are you running?

also which version of shell script? 2.0 or 1.9

you can try commenting these lines

https://github.com/esc0rtd3w/wifi-hacker/blob/87ccff059cb69727081d85bff3358cf8db37def3/wifi-hacker.sh#L5662

https://github.com/esc0rtd3w/wifi-hacker/blob/87ccff059cb69727081d85bff3358cf8db37def3/wifi-hacker.sh#L5663

or other references to NetworkManager can be commented to test

https://github.com/esc0rtd3w/wifi-hacker/blob/87ccff059cb69727081d85bff3358cf8db37def3/wifi-hacker.sh#L5675

https://github.com/esc0rtd3w/wifi-hacker/blob/87ccff059cb69727081d85bff3358cf8db37def3/wifi-hacker.sh#L1893

**Comment by muhammadfiqrih** [comment]
I want get me learn progammers

Pada tanggal 12 Feb 2019 9:30 AM, "Jason Borowski" <notifications@github.com>
menulis:

**Comment by unickq** [comment]
@arianizadi

I reproduced it. Also had looping.
Fixed by connecting to existing WiFi network

**Comment by mmuncan** [comment]
Hello!
@unickq you connected to a network before running the script or while it was looping? Coz none of both worked for me. and the suggestions comming from esc0rtd3w didn work for me either. What do i have to do now?

Thnx for ur answer! ;)
