### ISSUE TITLE
the second window can't open

### ISSUE THREAD

**Issue by chobitscao** [esc0rtd3w/wifi-hacker#3]
I'm using mac os x, I followed the step one by one and press enter after "THERE SHOULD NOW BE A NEW TERMINAL WINDOW OPEN", but didn't see any new terminal window open.

**Comment by esc0rtd3w** [comment]
This has not been tested on Mac. It is heavily tested on Backtrack R5 and Kali Linux 1.x. There will be a Mac port soon, or you can feel free to port it :)

**Comment by sashadev-sky** [comment]
@esc0rtd3w Also having this issue! I was wondering, how would I port it?
